name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  unit-testing-backend:
    name: Run Unit Tests Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run unit tests
        run: |
          cd backend
          npm test

  unit-testing-frontend:
    name: Run Unit Tests Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd html
          npm install

      - name: Run unit tests
        run: |
          cd html
          npm test

  # sonarqubeanalysis:
  #   name: Build and analyze
  #   runs-on: ubuntu-latest
  #   needs: [unit-testing-backend, unit-testing-frontend]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: sonarsource/sonarqube-scan-action@master
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #     - uses: sonarsource/sonarqube-quality-gate-action@master
  #       timeout-minutes: 5
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build-and-push:
    runs-on: ubuntu-latest
    #needs: [unit-testing-backend, unit-testing-frontend, sonarqubeanalysis]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout the repo
        uses: actions/checkout@v4
      -
        name: Build and push backend dockerfile
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-chat-backend:latest
      -
        name: Build and push frontend dockerfile
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./html
          file: ./html/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-chat-frontend:latest